name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build, Test and Analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake lcov gcovr g++ llvm

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="--coverage"

      - name: Build project
        run: cmake --build build

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure

      - name: Generate coverage report with gcovr
        run: |
          gcovr --root . --exclude 'test/*' --exclude 'build/*' --exclude 'main.cpp' --sonarqube -o build/coverage.xml

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v3
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Check Quality Gate
        uses: sonarsource/sonarqube-quality-gate-action@master
        with:
          scanMetadataReportFile: .scannerwork/report-task.txt
